[package]
name = "sum9"
version = "0.1.0"
edition = "2021"

[dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }

[[bench]]
name = "sum9_bruteforce"
harness = false

[[bench]]
name = "sum9_map"
harness = false
